spring:
  profiles:
    active: prod
server:
  port: 8433
  ssl:
    key-store-type: PKCS12
    key-store-password: nokiapnf
    key-store: classpath:keystore-local
    key-password: nokiapnf
    keyAlias: tomcat-localhost

management.endpoints.web.exposure.include: "loggers"


---
spring:
  profiles: dev
logging:
  level:
    org.onap.dcaegen2.services.prh: info
    org.onap.dcaegen2.services.sdk: info