spring:
  profiles: prod

server:
  port: 8433
  ssl:
    key-store-type: PKCS12
    key-store-password: nokiapnf
    key-store: classpath:keystore-local
    key-password: nokiapnf
    keyAlias: tomcat-localhost

management.endpoints.web.exposure.include: "loggers,refresh,env,health"

prh:
  workflow-scheduling-interval: 10s

---
spring:
  profiles: dev
logging:
  level:
    org.onap.dcaegen2.services.prh: debug
    org.onap.dcaegen2.services.sdk: debug

management.endpoints.web.exposure.include: "*"

---
spring:
  profiles:
    default: prod






