# ============LICENSE_START=======================================================
# PNF-REGISTRATION-HANDLER
# ================================================================================
# Copyright (C) 2026 Deutsche Telekom Intellectual Property. All rights reserved.
# ================================================================================
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ============LICENSE_END=========================================================
spring:
  profiles: prod

server:
  port: 8433
  ssl:
    key-store-type: PKCS12
    key-store-password: nokiapnf
    key-store: classpath:keystore-local
    key-password: nokiapnf
    keyAlias: tomcat-localhost

management.endpoints.web.exposure.include: "loggers,refresh,env,health"

---
spring:
  profiles: dev
logging:
  level:
    org.onap.dcaegen2.services.prh: debug
    org.onap.dcaegen2.services.sdk: debug

management.endpoints.web.exposure.include: "*"

---
spring:
  profiles:
    default: prod
